name: CSV to XML Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas lxml
    - name: Convert CSV to XML HW
      run: |
        python CSV_TO_XML_HW  # Zajistěte, že název souboru je správný
    - name: Upload XML to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './'
        publish_branch: gh-pages
